language: node_js
node_js:
  - '6'
before_script:
  - 'yarn global add bower'
  - 'bower install'
script: "yarn run build"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
