language: generic
services:
- docker
# At least Docker 17.05 is needed for multi-stage builds, so upgrade
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
script:
- docker build --no-cache --pull -t quay.io/areafiftylan/lancie-frontend:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
    docker tag quay.io/areafiftylan/frontend:$TRAVIS_BUILD_NUMBER quay.io/areafiftylan/frontend-beta:$TRAVIS_BUILD_NUMBER;
    docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD";
    docker push quay.io/areafiftylan/frontend-beta:$TRAVIS_BUILD_NUMBER;
  fi
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "live" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push wisvch/areafiftylan-frontend:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
   email: false
