language: node_js
node_js:
  - '6'
before_script:
  - 'npm install -g bower'
  - 'bower install'
script: "npm run build"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
